import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'fitstore.settings')
django.setup()

from products.models import Category, Product

# Clear existing data
Product.objects.all().delete()
Category.objects.all().delete()

# Create categories
supplements = Category.objects.create(name="Supplements", description="Protein powders, vitamins, and nutritional supplements")
clothing    = Category.objects.create(name="Clothing",     description="Gym wear and fitness apparel")
accessories = Category.objects.create(name="Accessories",  description="Equipment, tools, and training accessories")

# ── PRODUCTS ──────────────────────────────────────────────────────────────────
products_data = [

    # ── SUPPLEMENTS (1–10) ───────────────────────────────────────────────────
    {
        "name": "Alpha Pre-Workout X",
        "category": supplements,
        "description": "High-stimulant pre-workout formula for explosive energy, laser focus, and skin-splitting pumps.",
        "price": 44.99,
        "image_url": "/images/product-1.jpg",
        "benefits": "Boosts energy and endurance, enhances mental focus, increases blood flow for better pumps",
        "ingredients": "Beta-Alanine, Caffeine Anhydrous, L-Citrulline, Niacin, B12",
        "goal_tags": "muscle,fat_loss",
        "experience_level": "intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "mid",
        "stock": 60,
    },
    {
        "name": "Titan Whey Protein",
        "category": supplements,
        "description": "Premium whey protein isolate with 25g protein per serving. Fast-absorbing formula for post-workout recovery.",
        "price": 54.99,
        "image_url": "/images/product-2.jpg",
        "benefits": "Supports lean muscle growth, accelerates recovery, low in fat and carbs",
        "ingredients": "Whey Protein Isolate, Whey Protein Concentrate, Cocoa Powder, Natural Flavors, Stevia",
        "goal_tags": "muscle,general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore",
        "price_range": "mid",
        "stock": 80,
    },
    {
        "name": "Creatine Monohydrate Pro",
        "category": supplements,
        "description": "Micronised creatine monohydrate — the most researched supplement for strength and power output.",
        "price": 22.99,
        "image_url": "/images/product-3.jpg",
        "benefits": "Increases strength and power, enhances ATP production, supports lean muscle mass",
        "ingredients": "Creatine Monohydrate (micronised)",
        "goal_tags": "muscle",
        "experience_level": "intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 70,
    },
    {
        "name": "BCAA Recovery Fuel",
        "category": supplements,
        "description": "2:1:1 ratio BCAA formula with added electrolytes to fuel performance and speed up muscle recovery.",
        "price": 31.99,
        "image_url": "/images/product-4.jpg",
        "benefits": "Reduces muscle soreness, prevents muscle breakdown, replenishes electrolytes",
        "ingredients": "L-Leucine, L-Isoleucine, L-Valine, Sodium, Potassium, Vitamin B6",
        "goal_tags": "muscle,fat_loss",
        "experience_level": "intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 55,
    },
    {
        "name": "Mass Gainer Extreme",
        "category": supplements,
        "description": "High-calorie mass gainer with 1250 kcal per serving. Designed for hardgainers who struggle to put on size.",
        "price": 64.99,
        "image_url": "/images/product-5.jpg",
        "benefits": "Rapid calorie surplus for mass gain, complex carbs for sustained energy, 50g protein per serving",
        "ingredients": "Maltodextrin, Whey Protein Concentrate, Oat Flour, MCT Oil, Vitamins & Minerals",
        "goal_tags": "muscle",
        "experience_level": "beginner,intermediate",
        "dietary_preference": "omnivore",
        "price_range": "mid",
        "stock": 40,
    },
    {
        "name": "Thermo Burn Fat Burner",
        "category": supplements,
        "description": "Thermogenic fat burner combining green tea, cayenne, and L-carnitine for targeted fat loss.",
        "price": 37.99,
        "image_url": "/images/product-6.jpg",
        "benefits": "Boosts metabolism, suppresses appetite, enhances fat oxidation",
        "ingredients": "Green Tea Extract, Cayenne Pepper, L-Carnitine, CLA, Black Pepper Extract",
        "goal_tags": "fat_loss",
        "experience_level": "intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "mid",
        "stock": 50,
    },
    {
        "name": "Night Recovery Casein",
        "category": supplements,
        "description": "Slow-release micellar casein protein for overnight muscle repair and anti-catabolic protection.",
        "price": 49.99,
        "image_url": "/images/product-7.jpg",
        "benefits": "Sustained amino acid release for 7–8 hours, prevents overnight muscle breakdown, promotes deep sleep recovery",
        "ingredients": "Micellar Casein, Cocoa Powder, Sunflower Lecithin, Natural Vanilla Flavour",
        "goal_tags": "muscle",
        "experience_level": "intermediate,advanced",
        "dietary_preference": "omnivore",
        "price_range": "mid",
        "stock": 45,
    },
    {
        "name": "Electrolyte Hydration Mix",
        "category": supplements,
        "description": "Sugar-free electrolyte powder with sodium, magnesium, and potassium to keep you hydrated during intense training.",
        "price": 19.99,
        "image_url": "/images/product-8.jpg",
        "benefits": "Prevents cramping, maintains hydration, supports nerve and muscle function",
        "ingredients": "Sodium Chloride, Magnesium Citrate, Potassium Chloride, Vitamin C, Natural Flavours",
        "goal_tags": "general,fat_loss",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 90,
    },
    {
        "name": "Omega-3 Fish Oil Softgels",
        "category": supplements,
        "description": "High-strength fish oil with 1000mg EPA & DHA per serving for joint health and cardiovascular support.",
        "price": 24.99,
        "image_url": "/images/product-9.jpg",
        "benefits": "Reduces joint inflammation, supports heart health, improves cognitive function",
        "ingredients": "Fish Oil Concentrate (EPA 600mg, DHA 400mg), Gelatin Capsule",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore",
        "price_range": "budget",
        "stock": 100,
    },
    {
        "name": "Daily Multivitamin Performance",
        "category": supplements,
        "description": "Complete athlete multivitamin with 25 essential vitamins and minerals tailored for high-performance training.",
        "price": 29.99,
        "image_url": "/images/product-10.jpg",
        "benefits": "Fills nutritional gaps, boosts immune system, supports energy metabolism",
        "ingredients": "Vitamins A, C, D3, E, K2, B-Complex, Zinc, Magnesium, Selenium, Iron",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegetarian",
        "price_range": "budget",
        "stock": 120,
    },

    # ── CLOTHING (11–20) ─────────────────────────────────────────────────────
    {
        "name": "Compression Fit T-Shirt",
        "category": clothing,
        "description": "Muscle-hugging compression tee with 4-way stretch fabric and anti-odour technology.",
        "price": 34.99,
        "image_url": "/images/product-11.jpg",
        "benefits": "Enhances muscle awareness, moisture-wicking, reduces chafing",
        "sizing": "S, M, L, XL, XXL",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "mid",
        "stock": 80,
    },
    {
        "name": "Muscle Stringer Tank",
        "category": clothing,
        "description": "Wide-cut stringer vest for maximum freedom of movement during lifting. Lightweight and breathable.",
        "price": 22.99,
        "image_url": "/images/product-12.jpg",
        "benefits": "Ultimate ventilation, unrestricted shoulder mobility, gym-ready style",
        "sizing": "S, M, L, XL, XXL",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 100,
    },
    {
        "name": "Performance Gym Joggers",
        "category": clothing,
        "description": "Tapered joggers with zip pockets and drawstring waist. Perfect for the gym floor or warm-up.",
        "price": 49.99,
        "image_url": "/images/product-13.jpg",
        "benefits": "Tapered fit for clean look, stretch fabric for squats and lunges, zippered pockets keep essentials secure",
        "sizing": "XS, S, M, L, XL, XXL",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "mid",
        "stock": 60,
    },
    {
        "name": "Lightweight Training Shorts",
        "category": clothing,
        "description": "Ultra-light training shorts with built-in liner for comfort and support during any workout.",
        "price": 29.99,
        "image_url": "/images/product-14.jpg",
        "benefits": "Built-in compression liner, quick-dry fabric, side split for full range of motion",
        "sizing": "S, M, L, XL, XXL",
        "goal_tags": "general,fat_loss",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 75,
    },
    {
        "name": "Zip-Up Workout Hoodie",
        "category": clothing,
        "description": "Full-zip fleece hoodie for warm-up and cool-down. Kangaroo pocket and adjustable hood.",
        "price": 64.99,
        "image_url": "/images/product-15.jpg",
        "benefits": "Keeps muscles warm pre and post session, full zip for easy on/off, soft inner fleece",
        "sizing": "S, M, L, XL, XXL",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "mid",
        "stock": 55,
    },
    {
        "name": "Sleeveless Gym Hoodie",
        "category": clothing,
        "description": "Sleeveless pullover hoodie combining the look of a hoodie with the freedom of a vest.",
        "price": 42.99,
        "image_url": "/images/product-16.jpg",
        "benefits": "Full arm mobility, hoodie aesthetic, lightweight and breathable",
        "sizing": "S, M, L, XL, XXL",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "mid",
        "stock": 50,
    },
    {
        "name": "Breathable Training Cap",
        "category": clothing,
        "description": "Structured 6-panel training cap with mesh panels and moisture-wicking sweatband.",
        "price": 19.99,
        "image_url": "/images/product-17.jpg",
        "benefits": "Keeps sweat out of eyes, breathable mesh panels, adjustable strap",
        "sizing": "One size (adjustable)",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 120,
    },
    {
        "name": "Grip Training Gloves",
        "category": clothing,
        "description": "Half-finger weight lifting gloves with padded palm and wrist support strap.",
        "price": 24.99,
        "image_url": "/images/product-18.jpg",
        "benefits": "Protects palms from calluses, improves bar grip, wrist support on heavy lifts",
        "sizing": "S/M, L/XL",
        "goal_tags": "muscle,general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 90,
    },
    {
        "name": "Compression Leggings",
        "category": clothing,
        "description": "High-waist compression leggings with squat-proof fabric and side phone pocket.",
        "price": 54.99,
        "image_url": "/images/product-19.jpg",
        "benefits": "Squat-proof opacity, compresses muscles to reduce fatigue, high waist for core support",
        "sizing": "XS, S, M, L, XL",
        "goal_tags": "general,fat_loss",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "mid",
        "stock": 65,
    },
    {
        "name": "Athletic Crew Socks",
        "category": clothing,
        "description": "Cushioned crew socks with arch support and blister-guard stitching. Pack of 3 pairs.",
        "price": 14.99,
        "image_url": "/images/product-20.jpg",
        "benefits": "Arch compression reduces fatigue, cushioned sole for impact protection, moisture-wicking",
        "sizing": "S (UK 3–6), M (UK 6–9), L (UK 9–12)",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 150,
    },

    # ── ACCESSORIES (21–30) ──────────────────────────────────────────────────
    {
        "name": "Adjustable Dumbbell Set",
        "category": accessories,
        "description": "Space-saving adjustable dumbbells that replace 15 sets of weights. Quick-change dial system.",
        "price": 249.99,
        "image_url": "/images/product-21.jpg",
        "benefits": "Replaces entire dumbbell rack, weight adjusts in seconds, compact storage",
        "goal_tags": "muscle,general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "premium",
        "stock": 20,
    },
    {
        "name": "Olympic Barbell Kit",
        "category": accessories,
        "description": "20kg Olympic barbell with 60kg weight plate set and spring collars. Full starter kit.",
        "price": 189.99,
        "image_url": "/images/product-22.jpg",
        "benefits": "Complete lifting set, Olympic standard knurling, suited for bench, squat and deadlift",
        "goal_tags": "muscle",
        "experience_level": "intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "premium",
        "stock": 15,
    },
    {
        "name": "Resistance Band Pack",
        "category": accessories,
        "description": "Set of 5 latex resistance bands (10–50kg resistance) for home workouts, warm-ups, and rehab.",
        "price": 24.99,
        "image_url": "/images/product-23.jpg",
        "benefits": "Versatile full-body training, portable and lightweight, suitable for all levels",
        "goal_tags": "muscle,general,fat_loss",
        "experience_level": "beginner,intermediate",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 100,
    },
    {
        "name": "Powerlifting Belt",
        "category": accessories,
        "description": "10mm thick genuine leather powerlifting belt with lever buckle for maximum core support.",
        "price": 79.99,
        "image_url": "/images/product-24.jpg",
        "benefits": "Increases intra-abdominal pressure for heavier lifts, protects lower back, IPF legal",
        "sizing": "S (26–32\"), M (32–38\"), L (38–44\"), XL (44–50\")",
        "goal_tags": "muscle",
        "experience_level": "intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "premium",
        "stock": 30,
    },
    {
        "name": "Adjustable Workout Bench",
        "category": accessories,
        "description": "Multi-position adjustable bench with 7 back pad settings and 3 seat positions. Foldable for storage.",
        "price": 149.99,
        "image_url": "/images/product-25.jpg",
        "benefits": "Flat, incline, and decline positions, heavy-duty steel frame up to 300kg load, folds flat",
        "goal_tags": "muscle,general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "premium",
        "stock": 25,
    },
    {
        "name": "Kettlebell Pro Series",
        "category": accessories,
        "description": "Cast iron kettlebell with smooth powder coat finish and wide handle. Available in 8–32kg.",
        "price": 54.99,
        "image_url": "/images/product-26.jpg",
        "benefits": "Develops functional strength and conditioning, flat base for push-ups, wide grip for two-handed swings",
        "sizing": "8kg, 12kg, 16kg, 20kg, 24kg, 32kg",
        "goal_tags": "muscle,fat_loss,general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "mid",
        "stock": 40,
    },
    {
        "name": "Pull-Up Bar (Door Mount)",
        "category": accessories,
        "description": "No-drill door-mounted pull-up bar supporting up to 150kg. Fits most door frames 60–100cm wide.",
        "price": 34.99,
        "image_url": "/images/product-27.jpg",
        "benefits": "No installation needed, multiple grip positions, removable for travel",
        "goal_tags": "muscle,general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 60,
    },
    {
        "name": "Foam Roller Recovery Tool",
        "category": accessories,
        "description": "High-density EVA foam roller with grid texture for deep-tissue myofascial release.",
        "price": 27.99,
        "image_url": "/images/product-28.jpg",
        "benefits": "Reduces DOMS, improves flexibility, breaks up muscle knots and fascia adhesions",
        "goal_tags": "general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 80,
    },
    {
        "name": "Skipping Rope Pro Speed",
        "category": accessories,
        "description": "Bearing-based speed rope with aluminium handles and adjustable PVC cable. Double-under ready.",
        "price": 17.99,
        "image_url": "/images/product-29.jpg",
        "benefits": "Improves cardio and coordination, lightweight for travel, adjustable to any height",
        "goal_tags": "fat_loss,general",
        "experience_level": "beginner,intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 110,
    },
    {
        "name": "Wrist Wraps Support",
        "category": accessories,
        "description": "18-inch cotton wrist wraps with thumb loop and velcro closure for heavy pressing and overhead work.",
        "price": 16.99,
        "image_url": "/images/product-30.jpg",
        "benefits": "Stabilises wrists on max-effort lifts, reduces wrist pain, increases pressing strength",
        "sizing": "One size fits all (18\")",
        "goal_tags": "muscle",
        "experience_level": "intermediate,advanced",
        "dietary_preference": "omnivore,vegan,vegetarian",
        "price_range": "budget",
        "stock": 90,
    },
]

for product_data in products_data:
    Product.objects.create(**product_data)

print(f"✅ Created {len(products_data)} products across 3 categories!")


# ── CHAT SEEDING (keep existing) ───────────────────────────────────────────────
from chat.models import ChatSettings, CustomQAPair, ExternalKnowledgeItem

ChatSettings.objects.update_or_create(pk=1, defaults={
    "prioritize_custom_qa": True,
    "use_external_api": False,
})

CustomQAPair.objects.all().delete()
ExternalKnowledgeItem.objects.all().delete()

CustomQAPair.objects.bulk_create([
    CustomQAPair(
        question="What is your return policy?",
        answer="You can return unopened items within 14 days of delivery. Please contact support before sending the item back.",
        keywords="return,refund,policy",
        priority=1,
        use_as_priority_answer=True,
    ),
    CustomQAPair(
        question="How long does delivery take?",
        answer="Standard delivery normally takes 3 to 5 working days, depending on your location and stock availability.",
        keywords="delivery,shipping,arrival",
        priority=2,
        use_as_priority_answer=True,
    ),
    CustomQAPair(
        question="Which protein is best for beginners?",
        answer="Beginners usually do well with a simple whey protein or a plant-based protein if they prefer a vegan option. Start with one product and monitor how your body responds.",
        keywords="protein,beginner,starter",
        priority=3,
        use_as_priority_answer=True,
    ),
])

ExternalKnowledgeItem.objects.create(
    question="Do you restock sold-out products?",
    answer="Yes. Popular products are usually reviewed weekly for restocking, although timing can vary based on suppliers.",
    source_label="Seeded Knowledge",
)

print("✅ Seeded chat settings, custom FAQs, and external knowledge items!")
