# Generated by Django 4.2.8 on 2026-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritize_custom_qa', models.BooleanField(default=True, help_text='If enabled, admin-defined Q&A pairs are checked before external APIs and OpenAI.')),
                ('use_external_api', models.BooleanField(default=False, help_text='If enabled, the assistant can fetch answers from the configured external API.')),
                ('external_api_url', models.URLField(blank=True)),
                ('external_api_key', models.CharField(blank=True, max_length=255)),
                ('external_api_timeout', models.PositiveIntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Settings',
                'verbose_name_plural': 'Chat Settings',
            },
        ),
        migrations.CreateModel(
            name='CustomQAPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Optional comma-separated keywords to improve matching.', max_length=255)),
                ('match_type', models.CharField(choices=[('contains', 'Contains keyword'), ('exact', 'Exact question')], default='contains', max_length=20)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('use_as_priority_answer', models.BooleanField(default=True, help_text='When matched, prefer this answer over API/OpenAI responses.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Q&A Pair',
                'verbose_name_plural': 'Custom Q&A Pairs',
                'ordering': ['priority', '-updated_at', 'question'],
            },
        ),
        migrations.CreateModel(
            name='ExternalKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('source_label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Knowledge Item',
                'verbose_name_plural': 'External Knowledge Items',
                'ordering': ['question'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='matched_question',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response_source',
            field=models.CharField(choices=[('custom_qa', 'Custom Q&A'), ('external_api', 'External API'), ('openai', 'OpenAI'), ('rule_based', 'Rule Based')], default='rule_based', max_length=30),
        ),
    ]
