# Generated by Django 4.2.8 on 2026-04-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsettings_customqapair_externalknowledgeitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='response_source',
            field=models.CharField(choices=[('custom_qa', 'Custom Q&A'), ('external_api', 'External API'), ('openai', 'OpenAI'), ('rule_based', 'Rule Based'), ('smart_recommendation', 'Smart Recommendation')], default='rule_based', max_length=30),
        ),
    ]
