# Generated by Django 4.2.8 on 2026-01-25 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('benefits', models.TextField(help_text='Key benefits of the product')),
                ('ingredients', models.TextField(blank=True, help_text='For supplements: ingredients list')),
                ('sizing', models.CharField(blank=True, help_text='For clothing: size options', max_length=100)),
                ('goal_tags', models.CharField(blank=True, help_text='muscle,fat_loss,general', max_length=200)),
                ('experience_level', models.CharField(blank=True, help_text='beginner,intermediate,advanced', max_length=50)),
                ('dietary_preference', models.CharField(blank=True, help_text='omnivore,vegetarian,vegan', max_length=100)),
                ('price_range', models.CharField(blank=True, help_text='budget,mid,premium', max_length=50)),
                ('stock', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
