# Generated by Django 4.2.8 on 2026-01-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('muscle', 'Build Muscle'), ('fat_loss', 'Lose Fat'), ('general', 'General Fitness')], max_length=50)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('dietary_preference', models.CharField(choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=50)),
                ('budget', models.CharField(choices=[('budget', 'Budget ($)'), ('mid', 'Mid-range ($$)'), ('premium', 'Premium ($$$)')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
